Employees/urls.py
from django.urls import path
from .views import UserRegisterView, UserEditView

urlpatterns = [
    path('4040HIEnS/register/', UserRegisterView.as_view(), name='register'),
    path('4040HIEnS/edit_profile/', UserEditView.as_view(), name='edit_profile'),

]

RamCoreV3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/password_reset/', auth_views.PasswordResetView.as_view(), name='admin_password_reset'),
    path('admin/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('employees/', include('django.contrib.auth.urls')),
    path('employees/', include('Employees.urls')),
    path('', include('expresshub.urls')),


]

expresshub/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from ckeditor.fields import RichTextField

STATUS = ((0, 'Draft'), (1, 'Posted'))

STATUSM = ((0, 'Pending'), (1, 'In Process'), (2, 'Completed'))

STATUSH = ((0, 'Pending'), (1, 'In Process'), (2, 'Completed'))

UPSTAT = ((0, 'Upcoming'), (1, 'Completed'))

LOSTFOUND = ((0, 'Lost'), (1, 'Found'), (2, 'Claimed'))

DEPARTMENT = ((0, 'Operations'), (1, 'Sales'), (2, 'Maintenance'), (3, 'Housekeeping'))


class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null=True)
    createdate = models.DateTimeField(auto_now_add=True)
    updatedate = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS)
    views = models.ManyToManyField(User, related_name='user_viewed')

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        # return reverse('post_detail', args=(str(self.id)))
        return reverse('home')


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null=True)
    createdate = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=1)

    class Meta:
        ordering = ["-createdate"]

    def __str__(self):
        return "Comment {} by {}".format(self.body, self.author)


class Upcoming(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    details = RichTextField(blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    num_rooms = models.CharField(max_length=4)
    status = models.IntegerField(choices=UPSTAT, default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return reverse('post_detail', args=(str(self.id)))
        return reverse('upcoming')


class PostM(models.Model):
    titlem = models.CharField(max_length=255)
    authorm = models.ForeignKey(User, on_delete=models.CASCADE)
    bodym = RichTextField(blank=True, null=True)
    createdatem = models.DateTimeField(auto_now_add=True)
    updatedatem = models.DateTimeField(auto_now=True)
    statusm = models.IntegerField(choices=STATUSM, default=0)

    def __str__(self):
        return self.titlem + ' | ' + str(self.authorm)

    def get_absolute_url(self):
        # return reverse('post_detail', args=(str(self.id)))
        return reverse('maintenance')


class MComment(models.Model):
    postm = models.ForeignKey(PostM, on_delete=models.CASCADE, related_name="mcomments")
    mauthor = models.ForeignKey(User, on_delete=models.CASCADE)
    mbody = RichTextField(blank=True, null=True)
    mcreatedate = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-mcreatedate"]

    def __str__(self):
        return "Comment {} by {}".format(self.mbody, self.mauthor)


class PostH(models.Model):
    titleh = models.CharField(max_length=255)
    authorh = models.ForeignKey(User, on_delete=models.CASCADE)
    bodyh = RichTextField(blank=True, null=True)
    createdateh = models.DateTimeField(auto_now_add=True)
    updatedateh = models.DateTimeField(auto_now=True)
    statush = models.IntegerField(choices=STATUSH, default=0)

    def __str__(self):
        return self.titleh + ' | ' + str(self.authorh)

    def get_absolute_url(self):
        # return reverse('post_detail', args=(str(self.id)))
        return reverse('housekeeping')


class HComment(models.Model):
    posth = models.ForeignKey(PostH, on_delete=models.CASCADE, related_name="hcomments")
    hauthor = models.ForeignKey(User, on_delete=models.CASCADE)
    hbody = RichTextField(blank=True, null=True)
    hcreatedate = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-hcreatedate"]

    def __str__(self):
        return "Comment {} by {}".format(self.hbody, self.hauthor)


class LostFound(models.Model):
    item = models.CharField(max_length=255)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    description = RichTextField(blank=True, null=True)
    createdate = models.DateTimeField(auto_now_add=True)
    updatedate = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=LOSTFOUND, default=0)

    def __str__(self):
        return self.item + ' | ' + str(self.creator)

    def get_absolute_url(self):
        # return reverse('post_detail', args=(str(self.id)))
        return reverse('lostfound')


class LFComment(models.Model):
    lostfound = models.ForeignKey(LostFound, on_delete=models.CASCADE, related_name="lfcomments")
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null=True)
    createdate = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-createdate"]

    def __str__(self):
        return "Comment {} by {}".format(self.body, self.creator)


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    position = models.CharField(max_length=100)
    department = models.IntegerField(choices=DEPARTMENT)
    start_date = models.DateField(auto_now_add=False)
    profile_pic = models.ImageField(null=True, blank=True, upload_to="static/Images")

    def __str__(self):
        return str(self.user)

templates/add_lostfound.html
{% extends 'base.html' %}
{% block content %}

<header class="masthead bg-secondary">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-xs-8 col-xs-10 mx-auto bg-secondary">
        <div class="site-heading">
          <h2 class=" site-heading my-4 mt-3 text-white text-align:center">New Lost Item... </h2>
          </p>
        </div>
      </div>
    </div>
  </div>

</header>
<br/>

{% if user.is_authenticated %}

    <div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-secondary">Submit</button>
    </form>
    </div>

    <script>
        var name = "{{ user.id }}";
        document.getElementById("creator-userid").value=name;
    </script>

{% else %}
    <div class="container">
    <h4>You must be logged in to continue..</h4>
    </div>


{% endif %}
{% endblock %}

templates/add_posth.html
{% extends 'base.html' %}
{% block content %}

<header class="masthead bg-secondary">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-xs-8 col-xs-10 mx-auto bg-secondary">
        <div class="site-heading">
          <h2 class=" site-heading my-4 mt-3 text-white text-align:center">New Housekeeping Note... </h2>
          </p>
        </div>
      </div>
    </div>
  </div>

</header>
<br/>

{% if user.is_authenticated %}

    <div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-secondary">Submit</button>
    </form>
    </div>

    <script>
        var name = "{{ user.id }}";
        document.getElementById("auth-userid").value=name;
    </script>

{% else %}
    <div class="container">
    <h4>You must be logged in to continue..</h4>
    </div>


{% endif %}
{% endblock %}

templates/add_postm.html
{% extends 'base.html' %}
{% block content %}

<header class="masthead bg-secondary">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-xs-8 col-xs-10 mx-auto bg-secondary">
        <div class="site-heading">
          <h2 class=" site-heading my-4 mt-3 text-white text-align:center">New Maintenance Note... </h2>
          </p>
        </div>
      </div>
    </div>
  </div>

</header>
<br/>

{% if user.is_authenticated %}

    <div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-secondary">Submit</button>
    </form>
    </div>

    <script>
        var name = "{{ user.id }}";
        document.getElementById("auth-userid").value=name;
    </script>

{% else %}
    <div class="container">
    <h4>You must be logged in to continue..</h4>
    </div>


{% endif %}
{% endblock %}

templates/add_upcoming.html
{% extends 'base.html' %}

{% block content %}

<header class="masthead bg-secondary">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-xs-8 col-xs-10 mx-auto bg-secondary">
        <div class="site-heading">
          <h2 class=" site-heading my-4 mt-3 text-white text-align:center"> Add Upcoming Group or Event.. </h2>
        </div>
      </div>
    </div>
  </div>

</header>
<br/>

{% if user.is_authenticated %}

    <div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-secondary">Submit</button>
    </form>
    </div>

    <script>
        var name = "{{ user.id }}";
        document.getElementById("auth-userid").value=name;
    </script>

{% else %}
    <div class="container">
    <h4>You must be logged in to continue..</h4>
    </div>


{% endif %}
{% endblock %}

templates/author.html
{% extends 'base.html' %}

{% block content %}

<header class="masthead bg-secondary">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-xs-8 col-xs-10 mx-auto bg-secondary">
        <div class="site-heading">
          <h2 class=" site-heading my-4 mt-3 text-white text-align:center "> Posts By: {{ author }} </h2>
        </div>
      </div>
    </div>
  </div>

</header>

{% if author_posts %}
    {% if user.is_authenticated %}

        <div class="container">
          <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
              {% for post in author_posts %}
              <div class="card mb-4">
                <div class="card-body">
                  <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author.first_name }} {{ post.author.last_name }} | {{ post.createdate}}
                        <small><a href="{% url 'edit_post' post.pk %}">(Edit)</a></small> </p>
                  <hr>
                  <p class="card-text">{{post.body|slice:":200"|safe }}</p><br/><hr>
                  <a href="{% url 'post_detail' post.pk  %}" class="btn btn-primary">Read More &rarr;</a> <a href="{% url 'home' %}" class="btn btn-primary">Go Home &rarr;</a>
                </div>

              </div>
              {% endfor %}

            </div>
            {% block sidebar %}
            {% include 'sidebar.html' %}
            {% endblock sidebar %}
          </div>
        </div>
        {% if is_paginated %}
        <nav aria-label="Page navigation conatiner"></nav>
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
          {% endif %}
          {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

          {% endif %}
        </ul>
        {% endif %}

    {% else %}
        <div class="container">
        <h2 class=" site-heading my-4 mt-3 text-white text-align:center ">Active Posts</h2>
        </div>

    {% endif %}
{% else %}
    <h4>Sorry, this page does not exist...</h4>
{% endif %}
{% endblock %}

templates/authorh.html
{% extends 'base.html' %}

{% block content %}

<header class="masthead bg-secondary">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-xs-8 col-xs-10 mx-auto bg-secondary">
        <div class="site-heading">
          <h2 class=" site-heading my-4 mt-3 text-white text-align:center "> Posts By: {{ authorh }} </h2>
        </div>
      </div>
    </div>
  </div>

</header>

{% if authorh_posts %}
    {% if user.is_authenticated %}

        <div class="container">
          <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
              {% for posth in authorh_posts %}
              <div class="card mb-4">
                <div class="card-body">
                  <h2 class="card-title">{{ posth.titleh }}</h2>
                    <p class="card-text text-muted h6">{{ posth.authorh.first_name }} {{ posth.authorh.last_name }} | {{ posth.createdateh}}
                        <small><a href="{% url 'edit_posth' posth.pk %}">(Edit)</a></small> </p>
                  <hr>
                  <p class="card-text">{{posth.bodyh|slice:":200"|safe }}</p><br/><hr>
                  <a href="{% url 'posth_detail' posth.pk  %}" class="btn btn-primary">Read More &rarr;</a> <a href="{% url 'housekeeping' %}" class="btn btn-primary">Back to Housekeeping &rarr;</a>
                </div>

              </div>
              {% endfor %}

            </div>
            {% block sidebar %}
            {% include 'sidebar.html' %}
            {% endblock sidebar %}
          </div>
        </div>
        {% if is_paginated %}
        <nav aria-label="Page navigation conatiner"></nav>
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
          {% endif %}
          {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

          {% endif %}
        </ul>
        {% endif %}

    {% else %}
        <div class="container">
        <h2 class=" site-heading my-4 mt-3 text-white text-align:center ">Active Posts</h2>
        </div>

    {% endif %}
{% else %}
    <h4>Sorry, this page does not exist...</h4>
{% endif %}
{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
<title>Holiday Inn Express & Suites</title>
<link rel="stylesheet" href="{% static 'css/base.css' %}">

<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
<meta name="google" content="notranslate"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"/>

</head>

<body>


  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow" id="mainNav">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">Holiday Inn Express & Suites Dothan</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">


          {% if user.is_authenticated %}

              <li class="nav-item text-light">
              <a class="nav-link text-black font-weight-bold" href="{% url 'home' %}">ExpressHub Home</a>
              </li>

              <li class="nav-item text-light">
              <a class="nav-link text-black font-weight-bold" href="{% url 'add_post' %}">Add New Note</a>
              </li>

              <li class="nav-item text-light">
              <a class="nav-link text-black font-weight-bold" href="{% url 'drafts' %}">My Drafts</a>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link text-black font-weight-bold dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Maintenance</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'add_postm' %}">Add New Request</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'maintenance' %}">Pending Requests</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'maintenancecomp' %}">Completed Requests</a>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link text-black font-weight-bold dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Housekeeping</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'add_posth' %}">Add New Request</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'housekeeping' %}">Pending Requests</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'housekeepingcomp' %}">Completed Requests</a>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link text-black font-weight-bold dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Lost & Found</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'add_lostfound' %}">Add New Item</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'lostfound' %}">View Lost Bin</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'found' %}">View Found Bin</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'claimed' %}">View Claimed Items</a>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link text-black font-weight-bold dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Welcome, {{ user.first_name }}!</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'edit_profile' %}">Update Profile</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
              </li>

          {% else %}
              <li class="nav-item text-black">
              <a class="nav-link text-black font-weight-bold" href="{% url 'login' %}">Login</a>
              </li>

          {% endif %}

        </ul>
      </div>
    </div>
  </nav>


  {% block content %}
  <!-- Content Goes here -->
  {% endblock content %}

  <!-- Footer -->
  <footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Holiday Inn Express & Suites Dothan<br/>4090 Ross Clark Cir.<br/>Dothan, AL 36303<br/>
        <small>Powered by Forty-Two Begonias</small></p>
  </footer>
  <!-- bootstrap scripts -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
          integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
          integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
          integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>



</html>

templates/edit_lostfound.html
{% extends 'base.html' %}
{% block content %}

<header class="masthead bg-secondary">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-xs-8 col-xs-10 mx-auto bg-secondary">
        <div class="site-heading">
          <h2 class=" site-heading my-4 mt-3 text-white text-align:center ">Edit Lost Item..</h2>
        </div>
      </div>
    </div>
  </div>

</header>

{% if user.is_authenticated %}
    <br/>
        <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="btn btn-secondary">Submit &rarr;</button> <a href="{% url 'lostfound' %}" class="btn btn-secondary">Back to Lost & Found &rarr;</a>
        </form>
        </div>
{% else %}
        <br/>
        <h2 style="text-align:center">You must be logged in to view this page..</h2>
{% endif %}
{% endblock %}

templates/edit_posth.html
{% extends 'base.html' %}
{% block content %}

<header class="masthead bg-secondary">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-xs-8 col-xs-10 mx-auto bg-secondary">
        <div class="site-heading">
          <h2 class=" site-heading my-4 mt-3 text-white text-align:center ">Edit Housekeeping Note..</h2>
        </div>
      </div>
    </div>
  </div>

</header>

{% if user.is_authenticated %}
        <br/>
            <div class="container">
            <form method="POST">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button class="btn btn-secondary">Submit &rarr;</button> <a href="{% url 'housekeeping' %}" class="btn btn-secondary">Back to Housekeeping &rarr;</a>
            </form>
            </div>
{% else %}
        <br/>
        <h2 style="text-align:center">You must be logged in to view this page..</h2>
{% endif %}
{% endblock %}

templates/maintenancecomp.html
{% extends "base.html" %}

{% block content %}


<header class="masthead bg-secondary">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-xs-8 col-xs-10 mx-auto bg-secondary">
        <div class="site-heading">
          <h2 class=" site-heading my-4 mt-3 text-white text-align:center ">Completed Maintenance Requests</h2>
        </div>
      </div>
    </div>
  </div>

</header>

{% if user.is_authenticated %}

    <div class="container">
      <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
          {% for postm in postm_list %}
              <div class="card mb-4">
                <div class="card-body">
                  <h2 class="card-title">{{ postm.titlem }}<small> - (COMPLETED)</small></h2>
                    <p class="card-text text-muted h6"><a href="{% url 'authorm' postm.authorm.id %}">{{ postm.authorm.first_name }} {{ postm.authorm.last_name }}</a>
                        | {{ postm.updatedatem}} |
                     {% with postm.mcomments.count as total_mcomments %}
                        {{ total_mcomments }} comments
                     {% endwith %} | Status: {{ postm.get_statusm_display }} </p>
                  <hr>
                  <p class="card-text">{{postm.bodym|slice:":200"|safe }}</p><br/><hr>
                  <a href="{% url 'postm_detail' postm.pk %}" class="btn btn-primary">Read More &rarr;</a>
                  {% if user.id == 1 or user.id == 5 or user.id == 3 or user.id == 2 or user.id == postm.authorm.id %}
                    {% if postm.statusm == 0 or postm.statusm == 1 %}
                        <a href="{% url 'edit_postm' postm.pk %}" class="btn btn-primary">Edit Post &rarr;</a>
                    {% endif %}
                  {% endif %}
                  <a href="{% url 'maintenance' %}" class="btn btn-primary">Pending Requests &rarr;</a>
                </div>

              </div>
          {% endfor %}
        </div>
        {% block sidebar %}
        {% include 'sidebar.html' %}
        {% endblock sidebar %}
      </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation conatiner"></nav>
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
      {% endif %}
      {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

      {% endif %}
    </ul>
    {% endif %}

{% else %}
<br/>
<h2 style="text-align:center">You must be logged in to view this page..</h2>

{% endif %}
{%endblock%}